workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "qa"'
    - if: '$CI_COMMIT_BRANCH == "main"'

stages: [build, deploy]

build:
  stage: build
  tags: ["apienvios-shell"]
  script:
    - docker build -f docker/Dockerfile --target builder -t apienvios_ci:$CI_COMMIT_SHORT_SHA .

deploy:
  stage: deploy
  tags: ["apienvios-shell"]
  needs: ["build"]
  variables:
    GIT_STRATEGY: none
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - git -C /home/r4server/prod/apienvios fetch "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/apienvios/apienvios.git" "$CI_COMMIT_SHA"
    - git -C /home/r4server/prod/apienvios checkout --detach "$CI_COMMIT_SHA"
    - cd /home/r4server/prod/apienvios
    - docker compose build app
    - docker compose up -d --no-deps app
